server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # Fix for Bludit Pretty URLs
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Serve index.html for exact /sites
    location = /sites {
        alias /var/www/html/sites/;
        try_files index.html =404;
    }

    # Custom static sites
    location /sites/ {
        # Serve index.html for directory requests
        index index.html;
        # Try file, file.html, directory with index, else 404
        try_files $uri $uri.html $uri/ =404;
    }


    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}
